---
title: "CA_DataSimulation"
author: "Carina Ahrens"
date: "2024-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Modeled after Leahs Code

```{r}
humanities_grads_salary_params <- list(
  mu = 90000, # mean yearly income (low in humanities)
  alpha = c('n' = -5000,
            'y' = +20000
  ),
  beta = c('us' = 0,
           'int' = +1000
  ),
  # Not adding any interaction terms (gamma)
  sigma = 20000
)
```


```{r}
population_dist <- rnorm(100000, humanities_grads_salary_params$mu, humanities_grads_salary_params$sigma) #Currently using a normal distribution for simplicity. We can change later or use different distributions for other fields

sample_size <- 700 # only sampled part of data

humanities_grads <- expand.grid(
  post_doc = rep(NA, sample_size), 
  location = rep(NA),
  salary = NA
)

for (r in 1:nrow(humanities_grads)) {
  # randomly assign post-doc or not with proportion (0.3 post-doc, 0.7 not)
  humanities_grads$post_doc[r] <- sample(c('y', 'n'), size=1, prob=c(0.3, 0.7))
  # randomly assign location with proportion (0.4 international, 0.6 U.S.)
  humanities_grads$location[r] <- sample(c('us', 'int'), size=1, prob=c(0.4, 0.6))
  
  # Assign params based on pumpkin example
}
```


```{r}
for (j in 1:nrow(humanities_grads)) {
  pd <- as.character(humanities_grads$post_doc[j]) # temp. store post doc status
  loc <- as.character(humanities_grads$location[j])      # temp. store location         
  gamma <- 0                       #no interaction, so no combination factor needed
  humanities_grads$salary[j] <- (
    sample(population_dist, 1)                        #sample randomly from the population distribution
    + humanities_grads_salary_params$alpha[pd]                # assign expected impact of other variables
    + humanities_grads_salary_params$beta[loc]                
    + gamma                          
  )
}
```


```{r}
hist(humanities_grads$salary) #plot salary histogram

#mutate salary, altering scaling variables and mean of index distibution until desired mean impact and desired correlation between impact and salary is reached. Here, I picked mean h-index ~ 11 (based on a google search) and correlation ~0.3 (because we wanted h-index to be only weakly important in this field)
```


```{r}
humanities_grads <- humanities_grads |> 
  dplyr::mutate(h_index = humanities_grads$salary * 0.00005 + rnorm(700, 15, 5))
mean_impact <- mean(humanities_grads$h_index)
correlation <- cor(humanities_grads$salary, humanities_grads$h_index)
```


```{r}
hist(humanities_grads$h_index) #plot h-index values
```

# round two - forhigher h_index


```{r}
humanities_grads_H_salary_params <- list(
  mu = 140000, # mean yealy income
  alpha = c('n' = -5000,
            'y' = +20000
  ),
  beta = c('us' = 0,
           'int' = +1000
  ),
  # Not adding any interaction terms (gamma)
  sigma = 20000
)
```


```{r}
population_dist <- rnorm(100000, humanities_grads_H_salary_params$mu, humanities_grads_H_salary_params$sigma) #Currently using a normal distribution for simplicity. We can change later or use different distributions for other fields

sample_size <- 300

humanities_grads_H <- expand.grid(
  post_doc = rep(NA, sample_size), 
  location = rep(NA),
  salary = NA
)

for (r in 1:nrow(humanities_grads_H)) {
  # randomly assign post-doc or not with proportion (0.3 post-doc, 0.7 not)
  humanities_grads_H$post_doc[r] <- sample(c('y', 'n'), size=1, prob=c(0.3, 0.7))
  # randomly assign location with proportion (0.4 international, 0.6 U.S.)
  humanities_grads_H$location[r] <- sample(c('us', 'int'), size=1, prob=c(0.4, 0.6))
  
  # Assign params based on pumpkin example
}
```


```{r}
for (j in 1:nrow(humanities_grads_H)) {
  pd <- as.character(humanities_grads_H$post_doc[j]) # temp. store post doc status
  loc <- as.character(humanities_grads_H$location[j])      # temp. store location         
  gamma <- 0                       #no interaction, so no combination factor needed
  humanities_grads_H$salary[j] <- (
    sample(population_dist, 1)                        #sample randomly from the population distribution
    + humanities_grads_H_salary_params$alpha[pd]                # assign expected impact of other variables
    + humanities_grads_H_salary_params$beta[loc]                
    + gamma                          
  )
}
```


```{r}
hist(humanities_grads_H$salary) #plot salary histogram
```


```{r}
#mutate salary, altering scaling variables and mean of index distibution until desired mean impact and desired correlation between impact and salary is reached. Here, I picked mean h-index ~ 11 (based on a google search) and correlation ~0.3 (because we wanted h-index to be only weakly important in this field)

humanities_grads_H <- humanities_grads_H |> 
  dplyr::mutate(h_index = humanities_grads_H$salary * 0.00005 + rnorm(300, 30, 5))
mean_impact <- mean(humanities_grads_H$h_index)
correlation <- cor(humanities_grads_H$salary, humanities_grads_H$h_index)
```


```{r}
hist(humanities_grads_H$h_index) #plot h-index values
```


```{r}
data <- rbind(humanities_grads, humanities_grads_H)
data$fiedl <- "humanities"


hist(data$salary) #plot salary histogram
hist(data$h_index) #plot h-index values

plot(
  x = data$salary,
  y = data$h_index,
  cex = 1,
  pch = 21,
)



```
### Old Code - Does work but is not nice
```{r}
t.seed(12)
salery <- rnorm(n = 200, mean = 150000, sd = 8000);
hist(salery, xlab = "Random value (X)", col = "grey",
     main = "", cex.lab = 1.5, cex.axis = 1.5);

h_index <- rnorm(n = 200, mean = 55, sd = 15);
hist(h_index, xlab = "Random value (X)", col = "grey",
     main = "", cex.lab = 1.5, cex.axis = 1.5);

humanities_high <- data.frame(salery, h_index)
humanities_high$h_index_cat <- "high"
humanities_high$discipline <- "humanities"
humanities_high$country <- ""

salery <- rnorm(n = 800, mean = 90000, sd = 8000);
hist(salery, xlab = "Random value (X)", col = "grey",
     main = "", cex.lab = 1.5, cex.axis = 1.5);

h_index <- rnorm(n = 200, mean = 20, sd = 15);
hist(h_index, xlab = "Random value (X)", col = "grey",
     main = "", cex.lab = 1.5, cex.axis = 1.5);

humanities_low <- data.frame(salery, h_index)
humanities_low$h_index_cat <- "low"
humanities_low$discipline <- "humanities"
humanities_low$country <- ""
humanities <- rbind(humanities_high, humanities_low)

hist(humanities$salery, xlab = "Random value (X)", col = "grey",
     main = "", cex.lab = 1.5, cex.axis = 1.5)

hist(humanities$h_index, xlab = "Random value (X)", col = "grey",
     main = "", cex.lab = 1.5, cex.axis = 1.5)

plot(
  x = humanities$salery,
  y = humanities$h_index,
  cex = 1,
  pch=21
)


salery <- rnorm(n = 1000, mean = 120000, sd = 11000);
hist(salery, xlab = "Random value (X)", col = "grey",
     main = "", cex.lab = 1.5, cex.axis = 1.5);

h_index <- rnorm(n = 1000, mean = 40, sd = 15);
hist(h_index, xlab = "Random value (X)", col = "grey",
     main = "", cex.lab = 1.5, cex.axis = 1.5);

whatever <- data.frame(salery, h_index)
whatever$h_index_cat <- ""
whatever$discipline <- "whatever"
whatever$country <- ""

plot(
  x = whatever$salery,
  y = whatever$h_index,
  cex = 1,
  pch=21,
  )


data <- rbind(humanities, whatever)

#clrs <- c("red" = "humanities", "blue"="whatever")
plot(df_prob1$x1, df_prob1$x2, pch = df_prob1$y, col = clrs)

plot(
  x = data$salery,
  y = data$h_index,
  cex = 1,
  pch = 21,
)

```

