---
title: "JM_data_simulation"
author: "James Maze"
date: "2024-11-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(scales)
set.seed(42) # If you know, you know ! :)

```

## R Earth Sciences & Biology Distribution

```{r}

params <- list(
  mu = 95000,
  alpha = c('n' = -8000,
            'y' = +17000
  ),
  beta = c('us' = 0,
           'int' = +1000
  )
)

```

```{r}
sample_size <- 1000
gamma_size <- 1000

earth_bio_grads <- data.frame(
  post_doc = rep(NA, sample_size), 
  location = rep(NA, sample_size),
  field = 'Earth Science & Biology',
  salary = NA,
  h_index = NA
)

grads <- nrow(earth_bio_grads)

for (r in 1:grads) {
  # randomly assign post-doc or not with proportion (0.3 post-doc, 0.7 not)
  earth_bio_grads$post_doc[r] <- sample(c('y', 'n'), size=1, prob=c(0.3, 0.7))
  # randomly assign location with proportion (0.4 international, 0.6 U.S.)
  earth_bio_grads$location[r] <- sample(c('us', 'int'), size=1, prob=c(0.4, 0.6))
  
  # Assign params 
  pd <- as.character(earth_bio_grads$post_doc[r])
  loc <- as.character(earth_bio_grads$location[r])
  full_mu = params$mu
  alpha = params$alpha[pd]
  beta = params$beta[loc]
  
  sample_mu <- full_mu + alpha + beta
  print(sample_mu)
  
  sample_shape <- 5
  sample_rate <- (sample_shape / sample_mu)
  
  gamma_dist <- rgamma(gamma_size, shape = sample_shape, rate = sample_rate)
  
  # if (r %in% c(5, 67, 99, 300, 670, 900)) {
  #   hist(gamma_dist, breaks = 50, main = paste("Gamma Distribution (Iteration: with", pd, " and", loc,")"),
  #        xlab = "Value", probability = TRUE, col = "lightgreen")
  #   lines(density(gamma_dist), col = "blue", lwd = 2)
  # }
  
  salary <- sample(gamma_dist, size=1)
  print(salary)
  
  earth_bio_grads$salary[r] <- salary
  
}

```

```{r}

rho <- 0.75
sd <- rho / 2
print(sd)

earth_bio_grads <- earth_bio_grads %>% 
  mutate(h_index = salary * (1 + rnorm(1000, 0, sd))) %>% 
  mutate(h_index = case_when(h_index < 0 ~ 0,
                             h_index >= 0 ~ h_index)) %>% 
  mutate(h_index = h_index / 11000) %>% 
  mutate(discipline = 'Earth Sciences & Biology')

print(cor(earth_bio_grads$h_index, earth_bio_grads$salary))

options(scipen = 999 )

plot <- ggplot(data = earth_bio_grads, 
               mapping = aes(x=h_index, 
                             y=salary, 
                             color=post_doc)) +
  geom_point() +
  scale_x_continuous(labels = label_number()) +
  theme_bw() +
  labs(title="Correlation between h-index and income")

print(plot)
```
## Math and Statistics

```{r}

params <- list(
  mu = 95000,
  alpha = c('n' = -8000,
            'y' = +17000
  ),
  beta = c('us' = 0,
           'int' = +1000
  )
)

```

```{r}


```


